* Introduzione al corso
[me lo sono perso]
* Modalità di esame
[me lo sono perso]
** Prove in itinere
[me lo sono perso]
Se fai i compitini per gli appelli è come se avessi passato lo scritto
Puoi rifiutare la media dei compitini se vuoi
Per l'appello che rifiuti lo scritto entri con lo scritto
Per gli appelli dopo puoi anche entrare con la media dei compitini,
per l'appello per cui hai rifiutato no, rifiutare invalida i compitini
solo per quell'appello.

Le prove in itinere non sono limitate dalla propedeuticità
Poi arrivi alle prove orali e sticazzi

Puoi sostituire lo scritto con un progetto

Sia durante i compitini che per la modalità scritta non è permessa la
consultazione

Ora et Scriba lo stesso giorno
Scritto \to mezz'ora/ un paio d'ore \to Orale

* Modularitas
Non c'è propedeuticità tra ingenteria del software e basi di dati, per
quanto siano entrambi moduli di uno stesso corso integrato

Quindi devi:
 - Registratrti al primo
 - Registrarti al secondo
 - Registrarti all'appello di verbalizzazione

l'appello di verbalizzazione non devi fare niente dopo esserti
iscritto, è più un "Ecco gli ho fatto entrambi, se potesse
verbalizzarmi il corso integrato, grazie"

Chi ha il corso non integrato propedeuta Sysop
Chi ha il corso integrato propedeuta Al Quarizm
Tra i due moduli non propedeuta un cazzo

L'esito dei compitiini vale solo per gli appelli di gennaio e
febbraio, se non dai basi di dati in quei due mesi, se lo dai al di
fuori di quei mesi allora i compitini non valgono un cazzo

* Ricevimento
Giovedì
Mandare una mail in caso ci siamo /eventi inaspettati/ quel giovedì
che poi non può esserci e la cosa va male.
Ufficio aula 228 Santa Marta al secondo piano.

* Libri
Databases Illuminated
Catheride M. Ricardo, Susan D. Urban
Jones & Barlett Learning
(Se lo cercate su Google e siete fortunati c'è il pdf del libro)
(PIRATAAAAA)

molte delle slide sono riprese dal seguente libro
Basi di dati : Modelli e linguaggi di interrogazoine
P.Atzeni, S.Ceri, P.Fraternali, S.Paraboschi, R.Torlone
Ed. McGraw-Hill

un altro libro molto completo è il seguente
Sistemi di Basi di Dati - Fondamenti
R.A. Elmasri, S.B. Stocazzo

* Su moodle registratevi su basi di dati di quest'anno
Le slide rese disponibili via via

e Lab material, materiale per esercitazione

Materiali aggintivi quali
 - Pagine sul PostgreSQL
 - Esercizi per far pratica
