* Una base dati non è una tabella excel
Un singolo tabellone stile excel non è un'ottima idea
I dati sono rappresentati su più tabelle

Come gestisco dati rappresentati su più tabelle diverse, come metto in
relazoine tabelle diverse della stessa base dati?

* Modello basato su valori
Esempio per modello coso più tabelle

Organizzare le informazoini relative agli studenti di un ateneo e ai
cdl a cui sono iscritti

Costruisco due tabelle:
 - nome cognome data di nascita
 - nome dei cdl

Mario rossi è iscritto a ingengeria informatica
Voglio mettere in relazoine la riga di mario rossi con la riga di
ingegneria informatica.

Aggiungo alla prima tabella un altro attributo, un codice, un
attributo che porta univocamente con una riga della tabella dei cdl
(corsi di laurea, me lo ero scordato).

Il modello relazoine è un modello basato su valori, alcuni valori sono
usati per stabilire connessioni logiche tra tuple in tabelle diverse.

Potrei avere un caso più complesso con queste tabelle:
 - Nome cognome e data di nascita di ciascuno stundente
 - Nome degli inegnamenti del cdl
 - Esami superati da ciascuno studente con voti passati

una tabella studnete con matricola nome cognome e data
una tabella dei voti con Matricola Voto e Codice corso
una tabella con Insegnamenti Codice corso \leftrightarrow nome corso

Prima avevo utilizzo di puntatori, ma i puntatori sono direzionali, ce
ne vogliono 2, i puntatori non rappresentano informazoini utili,
mentre dare un codice a un corso può essere utile, dare una matrice a
uno studente può essere utile.

poi se vado a integrare il mio DMBS su un'architettura con un numero
diverso di bit vai a vedere che vado a farmi in culo.

* Definzoine formale
Lo schema di una relazione è costituito da una stringa, che è il nome
della relazione, e da un inseme di attributo

a ciascun attributo è associato un dominio, lo schema della relazoine
è rappresentato da relazoine e attributi
lo schema della base dati è rappresentato da il nome dello schema e da
tot relazioni con nomi distinti.

quindi abbiamo definito le intenstazioni delle tabelle

le istanze vengono definite passando per il concetto di n-upla o tupla
che associa a ciascuno dei valori stocazzo

se A \in X
t[A] la relazione che ha l'ennupla t sull'attributo A

La struttura dati usata per memorizzare una tupla è il record
i valori di una tupla su ciascun attributo corrispondono a boh

neppure a battitura è abbastanza veloce per capire che cazzo sta
dicendo con sti nessi logici.

* Relazioni su singoli attrbuti

In una base dati con signole relazioni, magari una tabella ha una
relazoine, una colonna definita solo sul sottinsieme degli studenti
lavoratori, aaa.

Prima abbiamo visto studente corso di laurea, studente esami superati,
e boh.

Ipergrafi e che cazzo ne so

* Wooclap
La soluzioe 1 fornisce un approccio più flessibile in quanto posso
posso avere
| Prodotto        | Fornitore          |
|-----------------+--------------------|
| prodotto        | fornitore          |
| stesso prodotto | un altro fornitore |

e anche
| Prodotto         | Fornitore        |
|------------------+------------------|
| prodotto         | fornitore        |
| prodotto diverso | stesso fornitore |

La soluzione 2, se ho più fornitori per uno stesso prodotto, fa
ripetere lo stesso prodotto su più righe per avere lo stesso prodotto
con valori diversi della colonna fornitore.
Non è flessibile, va piegata come il C++ che prova a fare
programmazione funzionale

La cosa porta a una *ridondanza* e nelle basi di dati la *ridondanza*
è per *deboli*

Per *ridondanza* si intende la ripetizoine di un dato che non è
necessario per idetificare univocamente quella riga nella tabella.

Non mi aggiungi un cazzo di informazoine, non servi a niente, sei solo
overhead, dovresti essere stato abortito retroattivamente prima di
fare così tante chiamate di sistema.

* Strutture nidificate
Spesso i dati da rappresentare non sono in relazoine 1 a 1.

* Esercizo

Libri
| Libro |                ISBN | Numero di collocazoine | Casa editrice(?) |
|-------+---------------------+------------------------+------------------|
| GOF   | 1111-1111-1111-1111 |              2222-2222 | Addison          |

Libri e autori
| Libro | Uno degli autori   |
|-------+--------------------|
| GOF   | uno della gang     |
| GOF   | due della gang     |
| GOF   | tre della gang     |
| GOF   | quattro della gang |

*gli autori vanno identificati in modo univoco*
| Codice univoco | Nome     | Cognome | Indirizzo    | Telefono         |
|     1234567890 | Giovanni | Rossi   | Via dei Neri | +39 123 456 7890 |

Case editrici
| Nome    | Sede | Recapito telefonico |
|---------+------+---------------------|
| Addison | Sede | Recapito            |

* Come gestisco il vuoto
Potrei usare un valore particolare del dominio per rappresentare il
fatto che non ho quel dato

non è dato che quel particolare valore che io uso per rappresentare
l'assenza di informazioni un domani non torni utile, e non il fatto
che manca l'informazoine di quel dato, ed ecco che nelle basi di dati
c'è un valore fuori da tutti i dominii che rappresenta l'assenza di
dato ed è il valore nullo.

Il valore nullo è usato in una base di dati per rappresentare
l'assenza di un dato, perchè non lo conosco o perchè so che non c'è,
non so quale sia la sua mail, non so se ha una mail, o so che non ha
una mail.

ora il problema è che il modello relazione è un modello basato su
valori, a seconda di dove compare il valore nullo porei avere una
problemi.
se non ho la data di nascita di mario rossi abbè, se non ho la
matricola di maria rossi sono un pochino nella merda, in quanto la
matricola viene usata per mettere gli studenti in relazione con cdl e
esami. In certi campi NON posso avere valori nulli.

questo pirta al concetto di vincoli e correttezza di una base dati,
oltre a boh ho bisogno di altri criteri per capire quando i dati sono
corretti e/o boh e/o hanno senso, quando per motivi vengono messi dati
non corretti non funzionanti che possono causare un tumore o boh.

è necessario introdurre dei vincoli di correttezza

* Vincoli
Le matricole devono essere diverse tra di loro e non nulle
Il voto non deve essere maggiore di 30
la lode non posso metterla a un voto diverso da 30
nel campo studnete mi aspetto di trovare la matricola di uno studnete
esistente nella tabella studente

Per evitare che si creino situazioni del genere è necessario
introdurre dei vincoli di integrità

queste funzioni danno un'occhiata alla tabella e rendono un valore
booleano

** Tipi di vincoli
*** Vincoli intrarelazionali
- vincoli di *dominio*
- vincoli di *ennupla*
- vincoli di *chiave*
*** Vincoli interrelazionali
- vincoli di *veni*
- vincoli di *vidi*
- vincoli di *vici*

Un buon progettista deve fare lo sforzo di specificare tutti i vincoli
alla creazoine della base dati, non specificare i vincoli non è un
bene o una furbizia è una... gigantesca stronzata per coglioni
lobotomizzati

**** vincoli di dominio
il valore che compare in un certo attributo deve appartenere al
dominio di quell'attributo
il voto deve essere un intero tra 18 e 30 inclusi, perchè non siamo la
conti che verbalizza le insufficienze[fn::stronza]
#+begin_src SQL
  (Voto >= 18) AND (Voto <=30)
#+end_src

#+begin_src SQL
  (Voto = 30) OR NOT (lode = "e lode")
#+end_src

**** Vincoli Internazionale
 - Non esistono due matricole uguali
 - Non ci sono ennuple uguali per nome, cognome, e data di nascita

Quando un insieme K di attributi che identifica univocamente una riga
allora quell'insieme è una *superchiave* allora K è una *superchiave*
*superchiave*.

K è una *chiave* se gode della proprietà di minimalità, se è una
*superchiave* minimale
Se non posso togliere nessun elemento senza che K smetta di essere una
superchiave, un minimo locale per dimensione nello spazio delle
superchiavi.

La minimalità è una caratteristica locale

** Altra roba sulle chiavi
In generale il concetto di chiave, se non siamo delle teste di cazzo,
deve riferirsi allo schema, e deve quindi valere per ogni istanza
sensata di quell'insieme.

Se non ho due studenti con la stessa data di nascita non è che la data
di nascita è una chiave, visto che è sensato che ci siano due studenti
con stessa data di nascita.

Data una relazoine chi ci dice che ci sia una chiave?

Se non possono esserci righe duplicate almeno l'intera riga è una
superchiave, visto che identifica univocamente la riga, se è minimale
allora abbiamo una chiave, l'intera riga, se non è minimale abbiamo
una chiave all'interno della riga come sottinsieme.


*** Valori nulli nelle chiavi
La presenza di valori nulli nelle chiavi deve essere limitata
Su questi attributi l'uso del valore nullo deve essere limitato

Chiave primaria, una chiave sulla quale *non sono ammessi* valori
nulli, di solito è sottolineata.

Nei DBMS è possibile dichiarare *UNA SOLA* chiave primaria per
tabella, *DEVE* essere univoca e *DEVE* essere non nulla

Se hai più attributi sottolineati vuol dire che quegli attributi,
insieme, formano una chiave primaria, niente vieta di avere altri
attributi usati come chiave, posso indicare chiavi oltre alla chiave
primaria, più chiavi hai meglio è che il DMBS costruisce
indicizzazioni più efficienti con più chiavi

**** Vincolo di integrità referenziale
*foreign key* per quando lo cercherai su www.en.wikipedia.org

Ogni codice che compare quando menziono un (coso) deve essere preso
dalla tabella chie definisce i (cosi)

Se ho una tabella studenti allora tutte le matricole nella tabella
voti devono essere presenti nella tabella studenti, se ho una
matricola non presente nella tabella studenti *so' cazzi*
uno studente non dichiarato non può avere voti, *SEGFAULT*

Niente vieta che lo studente compaia più volte o nessuna, ma deve
essere uno studente dichiarato nella tabella di prima.

Questa cosa può essere estesa a tabelle, a più attributi, a stocazzo.

Riguarda l'attributo di una tabella e la chiave primaria di un'altra
Questo vincolo è *asimmetrico*
Impone a tutti i valori di X, se diverso da nullo, di corrispondere a
uno dei valori della chiave nella tabella esterna
I valori della chiave devono comparire nella stessa tupla, stessa
riga, setssa wee wee hee hee mamma mia.

(comunque magari non so che vigile ha dato la multa e ho una chiave
nulla, se non è una chiave primaria magari boh mi sto fondendo è
venrdì e che cazzo mi piace lo stato solido della materia evviva
l'acqua)

* Operazioni su DMBS
 - posso fare ricerca (query)
 - posso fare aggiornamenti (update)
** Operazioni di aggiornamento e violazoine dei vincoli
