* Definizione viste prima
 - Distanza del codice
 - Segnala \leq s errori
 - Corregge \leq s errori

* Dimostriamo adesso
C \sube A_q^n
 1. C segnala \leq s errori \iff d(c) \geq s+1 (d(c) > s)
 2. C corregge \leq s errori \iff d(c) \geq s2+1 (d(c) > 2s)

Dim:
 1. Le palle non si intersecano
 2. Non sono gay


* Potere correttivo del codice
Si definisce come *potere correttivo del codice* il massimo numero di
errori che il codice può correggere
e(c) := \lfloor\frac{d(c) - 1}{2}\rfloor
(il max # di errori che c può correggere)

_Notazioni:_ Un (n,M,d)_q codice
\[C \sube A_q^n]\
inoltre M è la taglia del codice (=#= simbolino di cardinalità)
\[M = #(C)\]
e la distanza del codice è d
\[d = d(C)\]

* Codici lineari
Codici più usati nella pratica, faremo codici lineari finiti, questo
=q= è finito
Ad esempio =q = 2=, tipo in $\mathbb{F}_2$
introduciamo adesso i campi finiti

Stiamo per raggingere livelli hilbertiani di astrazione e minimalismo,
preparatevi.
** Campi finiti
*** Definiamo un anello
un _anello_ è una struttura (R;+;0_R ; \circ  ; 1_R)

=+= è un'operazione binaria in R \to R
il prodotto idem
1_R e 0_R \in R

**** Proprietà della somma
(R, \circ, 1_R) è un gruppo commutativo (o abeliano)
(vale la proprietà commutativa della somma)
valgono le seguenti proprietà dell'addizione
 - associativa (x + (y + z) = (x + y) + z)
 - commutativa (x + y = y + x)
 - 0_R è l'operatore neutro della somma
 - Proprietà di gruppo (\forall x \in R \exists (-x) \in R tale che x+(-x) \in R)

**** Proprietà del prodotto
(R, \circ, \1_R) è un monoide 
 - associativa x \circ (y \circ z) = (x \circ y) \circ z
 - 1_R è l'elemento neutro
 - non definiamo la proprietà commutativa (magari vuole che valga per matrici)
   ma se il prodotto è commutativo l'anello si dice commutativo
   la somma è sempre commutativa, il prodotto può non esserlo (*matriciiii*)

**** Proprietà di entrambi
 - proprietà distributiva di \circ \leftrightarrow + e di + \leftrightarrow \circ

*** Esempi di anelli e robe
Esempi di anelli commutativi
 - ($\mathbb{Z}$, +, 0;$\circ$ \circ , 1)
 - ($\mathbb{Q}$, +, 0; \circ, 1)
 - ($\mathbb{R}$, +, 0; \circ, 1)
 - ($\mathbb{C}$, +, 0; \circ, 1)

Esempi di anelli non commutativi
 - Le matrici (e che t'aspettavi?)
   (M_n,n ($\mathbb{C}$, +, [matrice nulla] ; \circ , [matrice identità]))

Altri anelli commutativi sono
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAa
 - ($\mathbb{F}_2$ = $\frac{\mathbb{Z}}{2}$ = {0,1}, +, 0; \circ, 1)
 - L'insieme dei polinomii a coefficienti reali e una sola variabile.

Altri esempii di anelli sono
 - [insert ogni cazzo di spazio vettoriale mai fatto dall'uomo]
   [inclusa la definizione astratta] [interface]

** Definizoine morfismo di anello
(lo facciamo nel caso commutativo visto che non ci interessano anelli
non commutativi, fanculo le matrici)

Siano R,S anelli commutativi (abuso di notazione per umanità)
un morfismo di di anelli è un'applicazione (una funzione in pratica) a
livello di insiemi
\varphi : R \to S tale che
 - \varphi rispetta le unità (\varphi(1_R) = 1_s)
 - \varphi rispetta la somma (\varphi (a +_R b) = \varphi(a) +_S \varphi(b))
 - \varphi rispetta il prodotto (\varphi (a \circ_R b) = \varphi(a) \circ_S \varphi(b))

non so se serve a trasformare espressioni R-ose in espressioni S-ose o
se fa da applicazione lineare
mi sa che servono a trasformare espressioni R-ose in espressioni S-ose

*** Esempi di morfisimi di anello
 1. $\mathbb{Z} \to \mathbb{Q} \to \mathbb{R} \to \mathbb{C}$
 2. $\mathbb{R}[x] \to R$ che va da p(x) a p(0)
 3. $\mathbb{R} \to \mathbb{R}[x]$ da \alpha al polinomio _\alpha_ costante

** Definizione di Ideale
Sia R un anello commutativo. un sottiniseme I \sube R si dice ideale in R
se
 - I \neq \empty
 - I chiuso rispetto alla somma (\nexists x,y \in I tali che x +_R y \notin I)
 - Assorbente rispetto al prodotto (se a \in R e b \in I allora a \circ _R
   b \in I)
    
proprietà di sto coso

1. Se I è ideale allora contiene l'elemento neutro rispetto alla
   somma (altrimenti fai la terza proprietà con lo 0 e sei nella
   merda, che puoi fare perchè I \neq \empty, allora (coso \in I) \circ 0_R = 0_R
   deve \in I, quindi 0_R \in I).

2. se 1_R \in I allora I = R fai la terza proprietà per ogni elemento
   di R e voilà, non scappi. 

3. se x \in I allora (-x) \in I 
   (tutti i multipli perchè suca multipli)

4. se R è un anello commutativo allora ci sono 2 ideali almeno, R
   stesso e l'insieme fatto dal solo 0, {0_R} in generale sono 2
   ideali distinti, ma può darsi che R = {0_R} (0_R è anche l'1_R
   dell'insieme, 0+0 fa 0, definisci la somma come "fa 0")

   abbiamo inoltre i coiddetti *ideali principali*
   (r) := tutti i multipli moltiplicativi di r
   \[{r \circ x | x \in R}\]
   detti ideale/principale di r
   (principale vuol dire generato da un solo elemento)

*** Esercizio
Determinare $Ideali(\mathbb{R})$
{0} = (0) e $\mathbb{R}$ sono ideali in $\mathbb{R}$
**** Ce ne sono altri?
supponiamo I \sube_ideale $\mathbb{R}$ e sappiamo che I \neq {0}, ci sarà un
\alpha \in I \alpha \neq 0 \to tutti i multipli di \alpha, ma siamo in $\mathbb{R}$
moltiplico tutto per \alpha \to ottengo tutto \to ottengo $\mathbb{R}$

Un altro modo sarebbe dire che 1_R \in I visto che \alpha \times
$frac{1}{\alpha}$ c'è, per la sucaggine degli ideali, quindi un'ideale con
1_R e contiene tutto

Non ce ne sono altri, gli unici due ideali di $\mathbb{R}$ sono {0} e
$\mathbb{R}$

quindi #(Ideali($\mathbb{R}$)) = 2, questa proprietà è caratteristica
dei *campi*
oltre a $\mathbb{R}$ abbiamo anche
 - #(Ideali($\mathbb{Q}$)) = 2
 - #(Ideali($\mathbb{C}$)) = 2
 - #(Ideali($\mathbb{F}_2$)) = 2

** Anello quoziente
Sarà un anello in cui l'insieme da cui si parte è un quozionte di una
realzione di equivalenza di che cazzo sta dicendo questo abbe'

*** Relazioni di equivalenza e loro quozienti
e dove trovarle.

Sia S un insieme
Una relazione di equivalenza sull'insieme S è un sottinsieme R del
prodotto cartesiano
R \sub S \times S
(quindi definiamo un grafo)
(un grafo connesso le cui componenti fortemente connesse sono le
classi di equivalenza)
(e quelle componenti fortemente connesse sono complete bidirezionali)

tale che questa sia
 - riflessiva $\forall x \in S \to (x,x) \in R$
 - simmetrica $(x,y) \in R \to (y,x) \in R$
 - transitiva $(x,y) \in R, (y,z) \in R \to (x,z) \in R$

**** Esempi
(dividiamo l'insieme in classi di equivalenza)
(classi di equivalenza, vale a dire sono uguali in qualche modo, ad
esempio per il resto modulo qualcosa)
(che saranno le componenti fortemente connesse di un grafo implicito
definito da R e S (R sono gli archi))
 - Classi di equivalenza modulo tot (x e y sono in relazione sse x-y è
   un multiplo di tot)

*** Definizione quiziente
Sia S un insieme e R una relazione di equivalenza in S.
Definisco l'insieme quoziente $\frac{S}{R}$ come l'insieme di tutte le
classi di R-equivalenza di elementi in S

Dove con classi di equivalenza di x \in S è l'insieme di tutti gli
elementi che sono uguali a x rispetto a R
Tutti gli elementi con cui x è in relazione rispetto a R.
\[[x]_R = {y \in S : x=_R y}\]

Ciascuna classe di equivalenza è un sottinsieme di S

Quindi \frac{S}{R} è un insieme i cui elementi sono particolari
sottinsiemi di S
(le classi di R-equivalenza in S)

*** Per esercizio
Dimostrare che:
 1. le classi di equivalenza di due elementi qualsiasi
    [x]_R e [y]_R allora questa uguaglianza di sottinsiemi è vera sse x
    e y sono in relazione secondo R (qui va usata la proprietà transitiva)
 2. se x \neq_R y allora le due classi sono diverse allora
    [x]_R inter [y]_R = \empty
 3. Unione di tutte le classi di equivalenza in S di stocazzo allora
    fanno S, grazialcazzo (è un po' una banalità)
    (\sube è un po' garantito, e che siano tutti gli elementi è un po'
    garantito, mettili insieme ed è un po' garantito)
    (usa la riflessività di R)

*** Esempio di... qualcosa


** Anelli e relazioni di equivalenza
Sia R un anello commutativo, I \sube R ideale
Considero la relazione di equivalenza R_I indotta da I

Dico che due elementi nell'anello sono in relazione sse la loro
differenza sta nell'ideale (stesso modo in cui abbiamo iniziato a fare
aritmetica modulare)
(non necessariamente ugaule all'ideale, cioè
(I.contains(x) = I.contains(y)) 

questa cosa è una relazione di equivalenza?
 - Riflessiva x =_R x? ja, 0_R \in I
 - Simmetrica? x =_R y \to x-y \in I
   y-x = -(x-y), la negazione sta nell'ideale, quindi
   y =_R x
 - Transitiva? Falla per esercizio

** Definizione importante
hai R e hai I \sube R ideale
$\frac{R}{I}$ si dice insieme quozioente di R rispetto all'ideale I
(o anche insieme quiziente di R modulo l'ideale I)

poi ci faremo una somma e un prodotto e elementi neutri e ci faremo un
bell'anellino
da qui definiremo un *anello quoziente* e raggiungeremo astrazioni da
far bagnare Platone
